const icons = [
    { name: 'Flutter', class: 'devicon-flutter-plain' },
    { name: 'React', class: 'devicon-react-original' },
    { name: 'JavaScript', class: 'devicon-javascript-plain' },
    { name: 'TypeScript', class: 'devicon-typescript-plain' },
    { name: 'HTML5', class: 'devicon-html5-plain' },
    { name: 'CSS3', class: 'devicon-css3-plain' },
    { name: 'TailwindCSS', class: 'devicon-tailwindcss-plain' },
    { name: 'Node.js', class: 'devicon-nodejs-plain' },
    { name: 'NestJS', class: 'devicon-nestjs-plain' },
    { name: 'Next.js', class: 'devicon-nextjs-plain' },
    { name: '.NET', class: 'devicon-dotnetcore-plain' },
    { name: 'Sass', class: 'devicon-sass-original' },
    { name: 'GitHub', class: 'devicon-github-original' },
    { name: 'MySQL', class: 'devicon-mysql-plain' },
    { name: 'Prisma', class: 'devicon-prisma-original' },
    { name: 'Google Cloud', class: 'devicon-googlecloud-plain' },
    { name: 'AWS', class: 'devicon-amazonwebservices-plain' },
    { name: 'ESLint', class: 'devicon-eslint-plain' },
    { name: 'Docker', class: 'devicon-docker-plain' },
    { name: 'ViteJS', class: 'devicon-vitejs-plain' },
    { name: 'Astro', class: 'devicon-astro-plain' },
];

export default icons;